graphite:
  build: ./graphite_api
  ports:
    - "8000:8000"
  links:
    - carbon
    - elasticsearch
  volumes_from:
    - carbon
elasticsearch:
  build: ./elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"
  links:
    - carbon
  volumes:
    - /var/lib/elasticsearch:/data
  hostname: elasticsearch
carbon:
  build: ./carbon
  ports:
    - "2003:2003"
    - "2004:2004"
  volumes:
    - /var/lib/whisper:/opt/graphite/storage/whisper